### ISSUE TITLE
Start button doesn't do anything

### ISSUE THREAD

**Issue by keyserfaty** [AgoraIO-Community/Agora-RN-Quickstart#34] opened 2020-03-29 20:11 UTC
Hi, I'm running the example on Android.
I added the appid and updated the channel name to a channel where I have another client connected. 
Pressing the 'Start call' button doesn't do anything. 
A console log here: 

``` js
RtcEngine.on('joinChannelSuccess', (data) => {                   //If Local user joins RTC channel
     console.log('here')
      RtcEngine.startPreview();                                      //Start RTC preview
      this.setState({
        joinSucceed: true,                                           //Set state variable to true
      });
    });
```

Never gets printed so I'm guessing its not connecting to the channel. Is there something else I should be changing from the initial codebase to make it work?
Thanks.

**Comment by LichKing-2234** [comment] 2020-03-30 03:45
@EkaanshArora can you take a look?

**Comment by EkaanshArora** [comment] 2020-03-31 16:35
Hey @keyserfaty, are you able to reproduce this issue, I tried starting a call with a channel having a user connected already and everything works as expected. Can you tell me the steps to reproduce the problem?

**Comment by tusharvikky** [comment] 2020-04-02 00:47
same here. Integrated in clean RN project. Start button triggers nothing.

**Comment by EkaanshArora** [comment] 2020-04-02 18:12
@tusharvikky, please make sure you're using the App ID without a certificate when generating one on agora.io, if this is the problem, I'll update the docs

**Comment by tusharvikky** [comment] 2020-04-02 21:15
@EkaanshArora This might be the problem. Documentation would be perfect.

**Comment by ziaulrehman40** [comment] 2020-04-14 10:52
Same issue, trying without certificate now. Is there a way to make it work with certificate?

**Comment by EkaanshArora** [comment] 2020-04-15 10:08
@ziaulrehman40 is it working without a certificate for you?

You can use a certificate by making the following changes:
In `Home.js` define your token in the state as `token:*your token here*`
In `Video.js` add `token: this.props.token` to your state and edit the joinChannel method to this: `RtcEngine.joinChannel(this.state.channelName, this.state.uid, `**`this.state.token`**`);`

**Comment by ziaulrehman40** [comment] 2020-04-15 10:23
Thanks @EkaanshArora I had figured this out after wasting some time and searching through the code of `react-native-agora` and seeing token parameter there.
I think this is a very common use case and should at-least be mentioned in readme of this repo of the agora library repo.

Also, as for the original issue. If there is anything which we can do to debug the issue, that should also be documented to close this issue.

Thanks again.

**Comment by plutoless** [comment] 2020-04-19 07:47
fixed in https://github.com/AgoraIO-Community/Agora-RN-Quickstart/pull/37

**Closed by plutoless** 2020-04-19 07:47 UTC

**Comment by meliodev** [comment] 2020-07-08 00:36
@keyserfaty please did it work for you ? I am facing the same issue since 3 days 😵

**Comment by keyserfaty** [comment] 2020-07-11 15:15
Haven't tried it again, sorry :(

**Comment by meliodev** [comment] 2020-07-11 15:41
It's Ok I fixed it. The issue was due to the certificate was enabled on my agora Dashboard.
