### ISSUE TITLE
Having problem building on IOS

### ISSUE THREAD

**Issue by fergMauricio** [AgoraIO-Community/Agora-RN-Quickstart#15] opened 2019-09-05 16:58 UTC
'React/RCTBridgeModule.h' file not found

Can you help me ?

**Comment by nipeow** [comment] 2019-09-05 17:41
'React/RCTBridgeModule.h' file not found 
It is what Xcode returns

**Comment by Matrixbirds** [comment] 2019-09-06 04:08
Pls provide u compiler log here that we could see what happened that need be fixed in the compilation

**Comment by hiscc** [comment] 2019-09-06 15:17
@Matrixbirds  some image like this, i met the same issue
<img width="830" alt="未命名" src="https://user-images.githubusercontent.com/17979372/64439365-60730f00-d0fc-11e9-990c-1328050c18ea.png">

**Comment by hiscc** [comment] 2019-09-06 15:24
直接 pod install 会报错
`[!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS":
  In Podfile:
    react-native-agora (from `../node_modules/react-native-agora`) was resolved to 2.9.0-alpha.1, which depends on
      AgoraRtcEngine_iOS (= 2.9)

None of your spec sources contain a spec satisfying the dependency: `AgoraRtcEngine_iOS (= 2.9)`.`

Xcode Version 10.3 (10G8)
pod Version  1.7.5

**Comment by nipeow** [comment] 2019-09-06 18:55
@Matrixbirds the problem is exactly what @hiscc had mentioned

**Comment by nipeow** [comment] 2019-09-06 18:57
Just for aditional data, on Android device works perfectly :)

**Comment by plutoless** [comment] 2019-09-06 22:48
Please try update your pod by running pod update.

**Comment by gabrielklose** [comment] 2019-09-09 11:43
![image](https://user-images.githubusercontent.com/26801238/64527944-9fac8600-d2dd-11e9-97a3-eaf772b9d2d1.png)


I have a similar problem, I tried to uninstall nodemodules, pod update, clean the ios build folder. But nothing works.

package.json:
{
  "name": "agoraguide",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-agora": "^2.9.0-alpha.1"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.9.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}


Podfile:
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'agoraguide' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for agoraguide

end

target 'agoraguide-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for agoraguide-tvOS

  target 'agoraguide-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end

**Comment by nipeow** [comment] 2019-09-09 21:02
@hiscc what is your Xcode version ?

**Comment by hiscc** [comment] 2019-09-10 03:07
> @hiscc what is your Xcode version ?

Version 10.3 (10G8)

**Comment by hiscc** [comment] 2019-09-10 03:23
Android demo also couldn't run！！
<img width="348" alt="未命名" src="https://user-images.githubusercontent.com/17979372/64581585-50d61d80-d3bd-11e9-9930-9d897d4a48e1.png">

**Comment by Matrixbirds** [comment] 2019-09-10 08:50
@hiscc  It seems you r missing libagora-rtc-sdk-jni.so, you could download it from agora sdk 2.9.0 android [demo](https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_v2_9_0_FULL.zip?_ga=2.261364429.1511066675.1567960966-827858851.1567960966)
and add the abi so to compiler and rebuild your project. It is issued by the 2.9.0 android sdk, our teammate will add x86-64 dependency in the next version ASAP.

**Comment by pappricot** [comment] 2019-09-15 02:12
Same issue missing <React/RCTLog.h>

**Comment by Matrixbirds** [comment] 2019-09-15 04:47
@pappricot Can u provide your compiler error log about missing `<React/RCTLog.h>` here?

**Comment by pappricot** [comment] 2019-09-15 18:08
<img width="268" alt="Screen Shot 2019-09-15 at 11 02 36 AM" src="https://user-images.githubusercontent.com/18382129/64925656-d3d5ea00-d7a8-11e9-967b-f41848d0cd13.png">

This morning when I re-cloned the project it gave me a different missing error. 

I also tried to use solution in https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/6, where you linked React dependencies manually, unfortunately it didn't work
<img width="432" alt="Screen Shot 2019-09-15 at 11 06 51 AM" src="https://user-images.githubusercontent.com/18382129/64925663-f10ab880-d7a8-11e9-8abd-9920f610b303.png">

Also as mentioned by some people, Android works fine for me

**Comment by Matrixbirds** [comment] 2019-10-31 17:39
@duanliwu 可以提交一下你的工程到你的github里吗？我去看一下？

**Comment by jenchote** [comment] 2019-11-22 10:55
This [link](https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found) solved my project pls take a look.

The solution in my case was to:

Disable the parallel builds:

Xcode menu -> Product -> Scheme -> Manage Shemes...
Double click on your application
Build tab -> uncheck Parallelize Build
Add react as a project dependecy

Xcode Project Navigator -> drag React.xcodeproj from Libraries to root tree
Build Phases Tab -> Target Dependencies -> + -> add React

**Comment by appectual** [comment] 2020-05-20 21:26
https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/15#issuecomment-543068345

Same Issue.

Tried this option:  https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/15#issuecomment-557487504

But in Target Dependencies couldn't find React.
Xcode Version:  Version 11.2.1 (11B500)

**Closed** 2020-06-12 03:42 UTC
